version: 2
updates:
  - package-ecosystem: "dotnet-sdk"
    directory: "/dotnet"
    schedule:
      interval: "weekly"
      day: "wednesday"
    ignore:
      - dependency-name: "*"
        update-types: 
          - "version-update:semver-major"
          - "version-update:semver-minor"
