# https://github.com/actions/ai-inference

name: AI Inference

on:
  workflow_dispatch:
    inputs:
      prompt:
        type: text
        description: 'The prompt to send to the model'
        required: true
        default: 'What can you do help?'

jobs:
  send-prompt:
    permissions:
      contents: read
      models: read
    runs-on: ubuntu-latest
    steps:
      - name: Test Local Action
        id: inference
        uses: actions/ai-inference@v1
        with:
          prompt: '${{ github.event.inputs.prompt }}'

      - name: Print Output
        id: output
        run: echo "${{ steps.inference.outputs.response }}" >> $GITHUB_STEP_SUMMARY
