name: .NET

on:
  push:
    branches: [ main ]
    paths:
    - 'dotnet/aspnetcore/**'
  workflow_dispatch:

env:
  DOTNET_VERSION: '6.0.x'
  SOURCE_CODE_PATH: 'razorpageapp/razorpageapp.csproj'
  BUILD_CONFIGURATION: Release

jobs:
  build:
    runs-on: ubuntu-latest
    
    defaults:
      run:
        working-directory: 'dotnet/aspnetcore'
        
    steps:
      - uses: actions/checkout@v2

      - name: Setup .NET
        uses: actions/setup-dotnet@v1
        with:
          dotnet-version: ${{ env.DOTNET_VERSION }}

      - name: Restore dependencies
        run: dotnet restore ${{ env.SOURCE_CODE_PATH }}

      - name: Build
        run: dotnet build --no-restore --configuration ${{ env.BUILD_CONFIGURATION }} ${{ env.SOURCE_CODE_PATH }}

      - name: Publish
        run: dotnet publish --no-build --configuration ${{ env.BUILD_CONFIGURATION }} --output ${{env.DOTNET_ROOT}}/myapp ${{ env.SOURCE_CODE_PATH }}

      - name: Upload artifact for deployment job
        uses: actions/upload-artifact@v2
        with:
          name: .net-app
          path: ${{env.DOTNET_ROOT}}/myapp

  deploy:
    runs-on: ubuntu-latest
    needs: build
    environment:
      name: 'Production'
      url: ${{ steps.deploy-to-webapp.outputs.webapp-url }}

    steps:
      - name: Download artifact from build job
        uses: actions/download-artifact@v2
        with:
          name: .net-app
          
      - name: 'Run Azure webapp deploy action using publish profile credentials'
        id: deploy-to-webapp
        uses: azure/webapps-deploy@v2
        with: 
          app-name: ${{ secrets.AZURE_WEBAPP_NAME }}
          slot-name: 'Production'
          publish-profile: ${{ secrets.AZURE_WEBAPP_PUBLISH_PROFILE }}
          package: .
