name: az login

on:
  workflow_dispatch:

jobs:
  az_login:
    runs-on: ubuntu-latest

    steps:
      - name: Azure Login
        uses: Azure/login@v1
        with:
          creds: ${{secrets.AZURE_CREDENTIALS}}

      - name: Show Azure regions
        run: az account list-locations 

      - name: Az CLI Logout
        run: az logout
