# https://learn.microsoft.com/en-us/azure/developer/github/connect-from-azure
# https://github.com/marketplace/actions/azure-login

name: Az CLI Login using OIDC

on:
  workflow_dispatch:

permissions:
  id-token: write
  contents: read

jobs:
  az-login-with-oidc:
    runs-on: ubuntu-latest
    environment: Production
    steps:
      - name: Az CLI Login
        uses: azure/login@v2
        with:
          client-id: ${{ secrets.AZURE_CLIENT_ID }}
          tenant-id: ${{ secrets.AZURE_TENANT_ID }}
          subscription-id: ${{ secrets.AZURE_SUBSCRIPTION_ID }}

      - name: Azure CLI script
        uses: azure/cli@v2
        with:
          azcliversion: latest
          inlineScript: |
            az account list-locations -o table

      - name: Az CLI Logout
        run: az logout
