# https://github.com/Azure/sql-action
name: Azure SQL using Connection String

on:
  workflow_dispatch:

permissions:
  id-token: write
  contents: read

jobs:
  connect_to_azure_sql:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v1
      
      - name: Az CLI Login
        uses: azure/login@v1
        with:
          client-id: ${{ secrets.AZURE_CLIENT_ID }}
          tenant-id: ${{ secrets.AZURE_TENANT_ID }}
          subscription-id: ${{ secrets.AZURE_SUBSCRIPTION_ID }}

      - name: Show database version
        uses: azure/sql-action@v2
        with:        
          connection-string: ${{ secrets.AZURE_SQL_CONNECTION_STRING }}
          path: './sqlscripts/version.sql'

      - name: Show tables
        uses: azure/sql-action@v2
        with:        
          connection-string: ${{ secrets.AZURE_SQL_CONNECTION_STRING }}
          path: './sqlscripts/show-tables.sql'

      - name: Az CLI Logout
        run: az logout
