# https://github.com/Azure/sql-action
name: Azure SQL using Connection String

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v1
      
      - name: Azure Login
        uses: Azure/login@v1
        with:
          creds: ${{ secrets.AZURE_CREDENTIALS }}

      - name: Show database version
        uses: azure/sql-action@v1.3
        with:        
          connection-string: ${{ secrets.AZURE_SQL_CONNECTION_STRING }}
          sql-file: './sqlscripts/version.sql'

      - name: Show tables
        uses: azure/sql-action@v1.3
        with:        
          connection-string: ${{ secrets.AZURE_SQL_CONNECTION_STRING }}
          sql-file: './sqlscripts/show-tables.sql'

      - name: Az CLI Logout
        run: az logout
