name: Azure App Service Settings

on:
  workflow_dispatch:
  
permissions:
  id-token: write
  contents: read

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Az CLI Login
        uses: azure/login@v1
        with:
          client-id: ${{ vars.AZURE_CLIENT_ID }}
          tenant-id: ${{ vars.AZURE_TENANT_ID }}
          subscription-id: ${{ vars.AZURE_SUBSCRIPTION_ID }}
      - name: Azure App Service Settings
        uses: Azure/appservice-settings@v1
        with:
          app-name: ${{ vars.AZURE_WEBAPP_NAME }}
          slot-name: 'Production'
          app-settings-json: '${{ secrets.AZURE_WEBAPP_APP_SETTINGS }}'
          general-settings-json: '${{ secrets.AZURE_WEBAPP_GENERAL_SETTINGS }}'
      - name: Az CLI Logout
        run: az logout
