# https://github.com/Azure/sql-action
name: Azure SQL using Connection String

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Azure Login
        uses: Azure/login@v1
        with:
          creds: ${{ secrets.AZURE_CREDENTIALS }}

      - uses: azure/sql-action@v1.3
        with:        
          connection-string: ${{ secrets.AZURE_SQL_CONNECTION_STRING }}
          sql-file: './sql/*.sql'
