# https://github.com/Azure/sql-action
name: Azure SQL using Connection String

on:
  workflow_dispatch:

permissions:
  id-token: write
  contents: read

jobs:
  connect-to-azure-sql:
    runs-on: ubuntu-latest

    steps:
      - name: Show database version
        uses: azure/sql-action@v2
        with:        
          connection-string: ${{ secrets.AZURE_SQL_CONNECTION_STRING }}
          path: './sqlscripts/version.sql'

      - name: Show tables
        uses: azure/sql-action@v2
        with:        
          connection-string: ${{ secrets.AZURE_SQL_CONNECTION_STRING }}
          path: './sqlscripts/show-tables.sql'
