# https://learn.microsoft.com/ja-jp/azure/developer/github/connect-from-azure
# https://github.com/Azure/actions-workflow-samples/blob/master/assets/create-secrets-for-GitHub-workflows.md

name: Az CLI Login using service principal

on:
  workflow_dispatch:

jobs:
  az-login:
    runs-on: ubuntu-latest

    steps:
      # https://github.com/fluffy-bunny/azure-login-action-act
      - name: Install Azure CLI
        if: github.actor == 'nektos/act'
        shell: bash
        run: |
          curl -sL https://aka.ms/InstallAzureCLIDeb | bash

      - name: Azure Login
        uses: Azure/login@v1
        with:
          creds: ${{secrets.AZURE_CREDENTIALS}}

      - name: Show Azure regions
        run: az account list-locations 

      - name: Az CLI Logout
        run: az logout
