name: Call REST API from Actions

on:
  workflow_dispatch:

jobs:
  call-rest-api:
    name: Call REST API
    runs-on: ubuntu-latest
    steps:
      - run: curl https://petstore.swagger.io/v2/pet/findByStatus?status=available | jq
