# https://github.com/marketplace/actions/checkout
name: Checkout other repository

on:
  workflow_dispatch:

jobs:
  own:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout own repository
        uses: actions/checkout@v3

      - name: Checkout my public repository
        uses: actions/checkout@v3
        with:
          repository: tsubakimoto/Enviewer
          ref: main
          path: Enviewer

      - name: Checkout my private repository
        uses: actions/checkout@v3
        with:
          repository: tsubakimoto/dotfiles
          token: ${{ secrets.PRIVATE_REPOSITORY_PAT }}
          path: dotfiles

  other:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout other public repository
        uses: actions/checkout@v3
        with:
          repository: dotnet-foundation/Home
          ref: main
          path: dotnet-foundation-home
