name: Build Nginx Image

on:
  workflow_dispatch:

env:
  WORKING_DIRECTORY: container/nginx
  IMAGE_TAG: $(date +%s)

jobs:

  build-nginx-image:

    runs-on: ubuntu-latest
    
    defaults:
      run:
        working-directory: ${{ env.WORKING_DIRECTORY }}

    steps:
    - uses: actions/checkout@v2
    - name: Build the Docker image
      run: docker build . --file Dockerfile --tag mynginx:${{ env.IMAGE_TAG }}
