# https://docs.github.com/ja/actions/using-jobs/running-jobs-in-a-container
name: Docker run in workflow

on:
  workflow_dispatch:

jobs:
  container-test-job:
    runs-on: ubuntu-latest
    container:
      image: node:14.16
      env:
        NODE_ENV: development
      ports:
        - 80
      volumes:
        - my_docker_volume:/volume_mount
      options: --cpus 1
    steps:
      - name: Check for dockerenv file
        run: (ls /.dockerenv && echo Found dockerenv && cat /.dockerenv) || (echo No dockerenv)
