name: GitHub Models from Actions

on:
  workflow_dispatch:

jobs:
  call-rest-api:
    name: Call GitHub Models
    runs-on: ubuntu-latest
    environment: Production
    steps:
      - run: |
          curl -X POST "https://models.inference.ai.azure.com/chat/completions" \
          -H "Content-Type: application/json" \
          -H "Authorization: Bearer ${{ secrets.GH_MODELS_PAT }}" \
          -d '{
              "messages": [
                  {
                      "role": "system",
                      "content": "You are a helpful assistant."
                  },
                  {
                      "role": "user",
                      "content": "What is the capital of Japan?"
                  }
              ],
              "temperature": 1.0,
              "top_p": 1.0,
              "max_tokens": 1000,
              "model": "gpt-4o-mini"
          }' | jq
