name: GitHub Models from Actions

on:
  workflow_dispatch:
    inputs:
      user-message:
        type: text
        required: false
        description: User message
        default: What is the capital of Japan?

jobs:
  call-rest-api:
    name: Call GitHub Models
    runs-on: ubuntu-latest
    environment: Production
    steps:
      - run: |
          curl -X POST "https://models.inference.ai.azure.com/chat/completions" \
            -H "Content-Type: application/json" \
            -H "Authorization: Bearer ${{ secrets.GH_MODELS_PAT }}" \
            -d '{
                "messages": [
                    {
                        "role": "system",
                        "content": "You are a helpful assistant."
                    },
                    {
                        "role": "user",
                        "content": "${{ inputs.user-message }}"
                    }
                ],
                "temperature": 0.5,
                "top_p": 1.0,
                "max_tokens": 1000,
                "model": "gpt-4o-mini"
            }' | jq -c '.choices[0].message.content' >> $GITHUB_STEP_SUMMARY
