name: Git tag creation

on:
  workflow_dispatch:
    inputs:
      tag-name:
        description: 'Tag name'
        type: string
        required: true
        
jobs:
  git-tag-creation:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - run: |
          echo "v${{ github.event.inputs.tag-name }}" > TAG_NAME
          git tag $TAG_NAME
          git push origin $TAG_NAME
