name: Git tag creation

on:
  workflow_dispatch:
    inputs:
      tag-name:
        description: 'Tag name'
        type: string
        required: true
        
jobs:
  git-tag-creation:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - run: |
          echo "Tag: ${{ github.event.inputs.tag-name }}"
          git tag ${{ github.event.inputs.tag-name }}
          git push origin ${{ github.event.inputs.tag-name }}
