name: GitHub pull request creation

on:
  workflow_call:
    inputs:
      branch-name:
        description: "Branch name"
        required: true
        type: string

env:
  BRANCH: ${{ inputs.branch-name }}
  TITLE: "PR from ${{ inputs.branch-name }}"

permissions:
  pull-requests: write

jobs:
  create-pull-request:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Dump parameters
        run: |
          echo "**branch name**"
          echo "$BRANCH"
          echo "**title**"
          echo $TITLE
      - name: Create a pull request
        run: |
          gh pr create \
            --base main \
            --head $BRANCH \
            --title "$TITLE" \
            --body ""
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
