# https://github.blog/security/supply-chain-security/configure-github-artifact-attestations-for-secure-cloud-native-delivery/
# https://github.blog/changelog/2024-06-25-artifact-attestations-is-generally-available/
name: GitHub Artifact Attestations

on:
  workflow_dispatch:

jobs:
  github-artifact-attestations:
    runs-on: ubuntu-latest

    permissions:
      id-token: write
      contents: read
      attestations: write

    defaults:
      run:
        working-directory: 'dotnet/net8.0'

    steps:
      - uses: actions/checkout@v4

      - name: Setup .NET
        uses: actions/setup-dotnet@v4
        with:
          global-json-file: dotnet/global.json

      - name: Publish
        run: dotnet publish --configuration Release --output ${{env.DOTNET_ROOT}}/myapp razorpageapp/razorpageapp.csproj

      - name: Artifact Attestation
        uses: actions/attest-build-provenance@v1
        with:
          subject-path: ${{env.DOTNET_ROOT}}/myapp
