name: GitHub pull request creation

on:
  workflow_call:
    inputs:
      branch-name:
        description: "Branch name"
        required: true
        type: string
    outputs:
      pull-request-url:
        description: "Pull Request URL"
        value: ${{ jobs.create-pull-request.outputs.pull-request-url }}

env:
  BRANCH: ${{ inputs.branch-name }}
  TITLE: "PR from ${{ inputs.branch-name }}"

jobs:
  create-pull-request:
    runs-on: ubuntu-latest
    outputs:
      pull-request-url: ${{ steps.pr.outputs.url }}
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Dump parameters
        run: |
          echo "**branch name**"
          echo "$BRANCH"
          echo "**title**"
          echo $TITLE
      - name: Create a pull request
        id: pr
        run: |
          url=$(gh pr create \
            --base main \
            --head $BRANCH \
            --title "$TITLE" \
            --body "")
          echo "url=$url" >> $GITHUB_OUTPUT
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
