# https://github.com/marketplace/actions/automatic-releases
name: Publish content to Release using marvinpinto/action-automatic-releases

on:
  workflow_dispatch:
    inputs:
      release-title:
        description: 'Release name'
        type: string
        default: 'my-release'
        required: true
      is-prerelease:
        description: 'Prerelease?'
        type: boolean
        default: true
        required: true

jobs:
  github-release-creation:
    runs-on: ubuntu-latest

    environment: release

    outputs:
      tag: ${{ steps.release.outputs.automatic_releases_tag }}
      url: ${{ steps.release.outputs.upload_url }}

    steps:
      - uses: actions/checkout@v3

      - name: Create a Release
        id: release
        uses: marvinpinto/action-automatic-releases@latest
        with:
          repo_token: ${{ secrets.GITHUB_TOKEN }}
          automatic_release_tag: ${{ inputs.release-title }}
          prerelease: ${{ inputs.is-prerelease }}
          title: ${{ inputs.release-title }}
          files: |
            README.md
