# https://github.com/skills/hello-github-actions
name: GitHub repository commit

on:
  workflow_dispatch:

env:
  BRANCH: content-${{ github.run_id }}

permissions:
  contents: write
  pull-requests: write

jobs:
  commit-on-branch:
    name: Commit a new file
    runs-on: ubuntu-latest
    outputs:
      branch-name: ${{ steps.commit-step.outputs.branch-name }}
    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          fetch-depth: 0
      - name: Prepare a branch, and file
        id: commit-step
        run: |
          echo -e "\n" >> README.md
          date >> README.md
          git checkout -b $BRANCH
          git config user.name github-actions[bot]
          git config user.email 41898282+github-actions[bot]@users.noreply.github.com
          git add .
          git commit -m "Add date to README.md"
          git push --set-upstream origin $BRANCH
          git checkout main
          echo "branch-name: $BRANCH"
          echo "branch-name=$BRANCH" >> $GITHUB_OUTPUT
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
  call-pull-request-workflow:
    name: Call pull request workflow
    needs: commit-on-branch
    uses: ./.github/workflows/github-pull-request-creation.yml
    with:
      branch-name: ${{ needs.commit-on-branch.outputs.branch-name }}
  show-pull-request-url:
    name: Show pull request url
    needs: call-pull-request-workflow
    runs-on: ubuntu-latest
    steps:
      - run: echo ${{ needs.call-pull-request-workflow.outputs.pull-request-url }}
