# https://docs.github.com/ja/actions/using-workflows/using-github-cli-in-workflows
# https://cli.github.com/manual/gh_repo_list
name: GitHub CLI List Repos

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: List repos
        run: gh repo list tsubakimoto --limit 10 --public
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
