# https://cli.github.com/manual/gh_issue

name: GitHub Issue Creation using GitHub CLI

on:
  workflow_dispatch:

jobs:
  create-issue-using-cli:
    runs-on: ubuntu-latest
    steps:
      - name: Create an issue
        run: |
          echo $GITHUB_REPOSITORY
          gh issue create --title "Some title" --body "Hello world" --repo $GITHUB_REPOSITORY
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        id: create-issue
      - run: 'echo Created issue number ${{ steps.create-issue.outputs.number }}'
      - run: 'echo Created ${{ steps.create-issue.outputs.url }}'
