name: GitHub pull request creation

on:
  workflow_call:
    inputs:
      branch-name:
        description: "Branch name"
        required: true
        type: string

env:
  TITLE: "PR from ${{ inputs.branch-name }}"

jobs:
  create-pull-request:
    runs-on: ubuntu-latest
    steps:
      - name: Create a pull request
        run: |
          gh pr create \
            --base ${{ inputs.branch-name }} \
            --title "$TITLE" \
            --body ""
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
