# https://www.memory-lovers.blog/entry/2022/11/20/180000
# https://docs.github.com/ja/actions/using-workflows/events-that-trigger-workflows#running-a-workflow-based-on-the-conclusion-of-another-workflow
name: Publish content to Release on tag creation

on:
  workflow_run:
    workflows: 
      - 'Git tag creation'
    types: 
      - 'completed'

jobs:
  github-release-creation-on-tag-creation:
    runs-on: ubuntu-latest
    
    steps:
      - uses: actions/checkout@v3
      
      - name: Create a Release
        id: release
        uses: marvinpinto/action-automatic-releases@latest
        with:
          repo_token: ${{ secrets.GITHUB_TOKEN }}
          prerelease: false
          files: |
            README.md
