# https://github.com/marketplace/actions/super-linter
name: Super Linter

on:
  # push:
  #   branches-ignore:
  #     - "main"
  pull_request:
    branches:
      - "main"
  workflow_dispatch:

jobs:
  linting:
    name: Lint Code Base
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: read
      statuses: write
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
      - name: Lint Code Base
        uses: super-linter/super-linter@v6
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
