name: Manual workflow

on:
  workflow_dispatch:
    inputs:
      name:
        description: 'Person to greet'
        default: 'World'
        required: true
      runner:
        description: 'GitHub hosted runner'
        default: 'ubuntu-latest'
        required: true
        type: choice
        options:
          - ubuntu-latest
          - ubuntu-24.04
          - ubuntu-22.04
          - ubuntu-20.04
          - windows-latest
          - windows-2022
          - windows-2019
          - macos-latest
          - macos-12
          - macos-11
          - macos-13
          - macos-14

jobs:
  greet:
    runs-on: ${{ github.event.inputs.runner }}
    steps:
    - name: Send greeting
      run: echo "Hello ${{ github.event.inputs.name }}"
