name: .NET 10.0 Script (shebang)

on:
  workflow_dispatch:

jobs:
  run-csharp-script:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: 'dotnet/net10.0/script'
    steps:
      - uses: actions/checkout@v4
      - name: Setup .NET
        id: setup
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: '10.0.x'
          dotnet-quality: 'preview'
      - name: Run app.cs
        run: |
          chmod +x app.cs
          ./app.cs
