name: ASP.NET Core 6.0 (Cached)

on:
  push:
    branches: [ main ]
    paths:
    - 'dotnet/net6.0/**'
  workflow_dispatch:

env:
  DOTNET_VERSION: '6.0.x'
  SOURCE_CODE_PATH: 'razorpageapp/razorpageapp.csproj'
  BUILD_CONFIGURATION: Release

jobs:
  build:
    runs-on: ubuntu-latest
    
    defaults:
      run:
        working-directory: 'dotnet/net6.0'
        
    steps:
      - uses: actions/checkout@v2

      - name: Setup .NET
        uses: actions/setup-dotnet@v1
        with:
          dotnet-version: ${{ env.DOTNET_VERSION }}

      - name: Cache nuget packages
        id: cache-nuget
        uses: actions/cache@v3
        env:
          cache-name: cache-nuget-packages
        with:
          path: ~/.nuget
          key: ${{ runner.os }}-build-${{ env.cache-name }}-${{ hashFiles('**/razorpageapp.csproj') }}
          restore-keys: |
            ${{ runner.os }}-build-${{ env.cache-name }}-
            ${{ runner.os }}-build-
            ${{ runner.os }}-

      - if: ${{ steps.cache-nuget.outputs.cache-hit != 'true' }}
        name: List the state of nuget packages
        continue-on-error: true
        run: dotnet nuget locals all --list

      - name: Restore dependencies
        run: dotnet restore ${{ env.SOURCE_CODE_PATH }}

      - name: Build
        run: dotnet build --no-restore --configuration ${{ env.BUILD_CONFIGURATION }} ${{ env.SOURCE_CODE_PATH }}

      - name: Publish
        run: dotnet publish --no-build --configuration ${{ env.BUILD_CONFIGURATION }} --output ${{env.DOTNET_ROOT}}/myapp ${{ env.SOURCE_CODE_PATH }}
