name: ASP.NET Core 9.0

on:
  push:
    branches: [ main ]
    paths:
    - 'dotnet/net9.0/**'
  workflow_dispatch:

env:
  SOURCE_CODE_PATH: 'razorpageapp/razorpageapp.csproj'
  BUILD_CONFIGURATION: Release

permissions:
  id-token: write
  contents: read

jobs:
  build-aspnetcore9:
    runs-on: ubuntu-latest
    
    defaults:
      run:
        working-directory: 'dotnet/net9.0'
        
    steps:
      - uses: actions/checkout@v4

      - name: Setup .NET
        id: setup
        uses: actions/setup-dotnet@v4
        with:
          global-json-file: dotnet/global.json

      - run: echo '${{ steps.setup.outputs.dotnet-version }}'

      - name: Restore dependencies
        run: dotnet restore ${{ env.SOURCE_CODE_PATH }}

      - name: Build
        run: dotnet build --no-restore --configuration ${{ env.BUILD_CONFIGURATION }} ${{ env.SOURCE_CODE_PATH }}

      - name: Publish
        run: dotnet publish --no-build --configuration ${{ env.BUILD_CONFIGURATION }} --output ${{env.DOTNET_ROOT}}/myapp ${{ env.SOURCE_CODE_PATH }}

      - name: Upload artifact for deployment job
        uses: actions/upload-artifact@v4
        with:
          name: .net-app
          path: ${{env.DOTNET_ROOT}}/myapp

  deploy-aspnetcore9:
    runs-on: ubuntu-latest
    needs: build-aspnetcore9
    environment:
      name: 'Production'
      url: ${{ steps.deploy-to-webapp.outputs.webapp-url }}
    steps:
      - name: Download artifact from build job
        uses: actions/download-artifact@v4
        with:
          name: .net-app
          
      - name: Az CLI Login
        uses: azure/login@v2
        with:
          client-id: ${{ secrets.AZURE_CLIENT_ID }}
          tenant-id: ${{ secrets.AZURE_TENANT_ID }}
          subscription-id: ${{ secrets.AZURE_SUBSCRIPTION_ID }}

      - name: 'Run Azure webapp deploy action'
        id: deploy-to-webapp
        uses: azure/webapps-deploy@v3
        with: 
          app-name: ${{ vars.AZURE_WEBAPP_NAME }}-dotnet9
          slot-name: 'Production'
          package: .

      - name: Az CLI Logout
        run: az logout
