# https://docs.github.com/ja/packages/managing-github-packages-using-github-actions-workflows/publishing-and-installing-a-package-with-github-actions
# https://docs.github.com/ja/packages/working-with-a-github-packages-registry/working-with-the-nuget-registry
name: Publish a package for netstandard2.0

on:
  workflow_dispatch:

env:
  WORKING_DIRECTORY: 'dotnet/netstandard2.0/Standard20Library'

permissions:
  contents: read
  packages: write

jobs:
  build-package:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ${{ env.WORKING_DIRECTORY }}
    steps:
      - uses: actions/checkout@v3
      - name: Setup .NET
        uses: actions/setup-dotnet@v3
        with:
          global-json-file: './dotnet/global.json'
      - name: Build
        run: |
          dotnet build --configuration Release
      - name: Pack
        run: |
          dotnet pack --no-build --configuration Release
      - name: Upload artifact
        uses: actions/upload-artifact@v4
        with:
          name: nuget-packages
          path: '**/*.nupkg'

  publish-package:
    runs-on: ubuntu-latest
    needs: build-package
    steps:
      - uses: actions/download-artifact@v4
        with:
          name: nuget-packages
          path: ${{ env.WORKING_DIRECTORY}}
      - name: Prepare
        run: |
          dotnet nuget add source --username tsubakimoto --password ${{ secrets.GITHUB_TOKEN }} --store-password-in-clear-text --name github "https://nuget.pkg.github.com/tsubakimoto/index.json"
      - name: Publish
        run: |
          dotnet nuget push **/*.nupkg --source "github"
