name: Nodejs Express

on:
  push:
    branches: [ main ]
    paths:
    - 'nodejs/express/**'
  workflow_dispatch:

env:
  WORKING_DIRECTORY: nodejs/express

permissions:
  id-token: write
  contents: read

jobs:
  build-express:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ${{ env.WORKING_DIRECTORY }}
    steps:
      - uses: actions/checkout@v4

      - name: Set up Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '16.x'
          cache: 'npm'
          cache-dependency-path: ${{ env.WORKING_DIRECTORY }}

      - name: npm install, build, and test
        run: |
          npm install
          npm run build --if-present
          npm run test --if-present

      - name: Upload artifact for deployment job
        uses: actions/upload-artifact@v4
        with:
          name: node-app
          path: ${{ env.WORKING_DIRECTORY }}

  deploy-express:
    runs-on: ubuntu-latest
    needs: build-express
    environment:
      name: 'Production'
      url: ${{ steps.deploy-to-webapp.outputs.webapp-url }}
    steps:
      - name: Download artifact from build job
        uses: actions/download-artifact@v4
        with:
          name: node-app

      - name: Az CLI Login
        uses: azure/login@v1
        with:
          client-id: ${{ secrets.AZURE_CLIENT_ID }}
          tenant-id: ${{ secrets.AZURE_TENANT_ID }}
          subscription-id: ${{ secrets.AZURE_SUBSCRIPTION_ID }}

      - name: 'Run Azure webapp deploy action'
        id: deploy-to-webapp 
        uses: azure/webapps-deploy@v3
        with:
          app-name: ${{ vars.AZURE_WEBAPP_NAME }}-express
          slot-name: 'Production'
          package: .

      - name: Az CLI Logout
        run: az logout
