name: Nodejs Express with Zip

on:
  push:
    branches: [ main ]
    paths:
    - 'nodejs/express/**'
  workflow_dispatch:

env:
  WORKING_DIRECTORY: nodejs/express
  PACKAGE_NAME: node-app
  ARCHIVE_NAME: express.zip

permissions:
  id-token: write
  contents: read

jobs:
  build-express-zip:
    runs-on: ubuntu-latest

    defaults:
      run:
        working-directory: ${{ env.WORKING_DIRECTORY }}

    steps:
      - uses: actions/checkout@v4

      - name: Set up Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '16.x'
          cache: 'npm'
          cache-dependency-path: ${{ env.WORKING_DIRECTORY }}

      - name: npm install, build, and test
        run: |
          npm install
          npm run build --if-present
          npm run test --if-present

      - name: Install zip
        uses: montudor/action-zip@v1

      - name: Zip output
        run: zip -qq -r ${{ env.ARCHIVE_NAME }} .
        working-directory: ${{ env.WORKING_DIRECTORY }}

      - name: Upload artifact for deployment job
        uses: actions/upload-artifact@v4
        with:
          name: ${{ env.PACKAGE_NAME }}
          path: ${{ env.WORKING_DIRECTORY }}/${{ env.ARCHIVE_NAME }}

  deploy-express-zip:
    runs-on: ubuntu-latest
    needs: build-express-zip
    environment:
      name: 'Production'
      url: ${{ steps.deploy-to-webapp.outputs.webapp-url }}
    steps:
      - name: Download artifact from build job
        uses: actions/download-artifact@v4
        with:
          name: ${{ env.PACKAGE_NAME }}

      - name: Az CLI Login
        uses: azure/login@v2
        with:
          client-id: ${{ vars.AZURE_CLIENT_ID }}
          tenant-id: ${{ vars.AZURE_TENANT_ID }}
          subscription-id: ${{ vars.AZURE_SUBSCRIPTION_ID }}

      - name: 'Deploy to Azure WebApp'
        id: deploy-to-webapp 
        uses: azure/webapps-deploy@v2
        with:
          app-name: ${{ vars.AZURE_WEBAPP_NAME }}-express
          slot-name: 'Production'
          package: ${{ env.ARCHIVE_NAME }}

      - name: Az CLI Logout
        run: az logout
