name: Build and deploy Python FastAPI app to Azure Web App

on:
  push:
    branches: [ main ]
    paths:
    - 'python/fastapi/**'
  workflow_dispatch:

env:
  PYTHON_VERSION: '3.7'
  AZURE_WEBAPP_NAME: 'app-yuta-github-actions-samples'
  AZURE_WEBAPP_PACKAGE_PATH: './python/fastapi'

jobs:
  build:
    runs-on: ubuntu-latest

    defaults:
      run:
        working-directory: 'python/fastapi'

    steps:
      - uses: actions/checkout@v2

      - name: Set up Python version
        uses: actions/setup-python@v1
        with:
          python-version: ${{ env.PYTHON_VERSION }}

      - name: Install dependencies
        run: pip install -r requirements.txt
      
      - name: Building web app
        uses: azure/appservice-build@v2
          
      - name: Deploy to Azure Web App
        uses: azure/webapps-deploy@v2
        id: deploy-to-webapp
        with:
          app-name: ${{ env.AZURE_WEBAPP_NAME }}
          slot-name: 'Production'
          publish-profile: ${{ secrets.AZURE_WEBAPP_PUBLISH_PROFILE }}
          package: ${{ env.AZURE_WEBAPP_PACKAGE_PATH }}
