name: Python FastAPI

on:
  push:
    branches: [ main ]
    paths:
    - 'python/fastapi/**'
  workflow_dispatch:

env:
  WORKING_DIRECTORY: python/fastapi

permissions:
  id-token: write
  contents: read

jobs:
  build-fastapi:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ${{ env.WORKING_DIRECTORY }}
    steps:
      - uses: actions/checkout@v4

      - name: Set up Python version
        uses: actions/setup-python@v4
        with:
          python-version: '3.12'

      - name: Create and start virtual environment
        run: |
          python -m venv venv
          source venv/bin/activate
      
      - name: Install dependencies
        run: pip install -r requirements.txt
        
      - name: Upload artifact for deployment jobs
        uses: actions/upload-artifact@v4
        with:
          name: python-app
          path: |
            ./${{ env.WORKING_DIRECTORY }}
            !./${{ env.WORKING_DIRECTORY }}/venv/
      
  deploy-fastapi:
    runs-on: ubuntu-latest
    needs: build-fastapi
    environment:
      name: 'Production'
      url: ${{ steps.deploy-to-webapp.outputs.webapp-url }}
    steps:
      - name: Download artifact from build job
        uses: actions/download-artifact@v4
        with:
          name: python-app
          
      - name: Az CLI Login
        uses: azure/login@v2
        with:
          client-id: ${{ secrets.AZURE_CLIENT_ID }}
          tenant-id: ${{ secrets.AZURE_TENANT_ID }}
          subscription-id: ${{ secrets.AZURE_SUBSCRIPTION_ID }}

      - name: Azure App Service Settings
        uses: Azure/appservice-settings@v1
        with:
          app-name: ${{ vars.AZURE_WEBAPP_NAME }}-fastapi
          slot-name: 'Production'
          app-settings-json: '[{"name":"SCM_DO_BUILD_DURING_DEPLOYMENT","value":"1","slotSetting":false}]'
  
      - name: 'Deploy to Azure Web App'
        uses: azure/webapps-deploy@v3
        id: deploy-to-webapp
        with:
          app-name: ${{ vars.AZURE_WEBAPP_NAME }}-fastapi
          slot-name: 'Production'
          package: .

      - name: Az CLI Logout
        run: az logout
