name: Reusable Workflow (call context)

on:
  workflow_dispatch:

jobs:
  call-context-workflow:
    uses: .github/workflows/github-actions-context-dump.yml@main
    with:
      config-path: README.md
    secrets:
      envPAT: ${{ secrets.token }}
