name: Various triggers workflow

on:
  issues:
    types: [opened, edited, deleted, transferred, pinned, unpinned, closed, reopened, assiged, unassigned, labeled, unlabeled, locked, unlocked, milestoned, demilestoned]
  discussion:
    types: [created, edited, deleted, answered, pinned, unpinned, labeled, unlabeled, locked, unlocked]
  discussion_comment:
    types: [created, edited, deleted]
  workflow_dispatch:

jobs:
  dump:
    runs-on: ubuntu-latest
    steps:
    - name: Dump context
      run: echo "${{ toJSON(github) }}"

  issue:
    runs-on: ubuntu-latest
    if: github.event.issue
    steps:
    - name: Issue controling
      run: echo "Triggered on issue by ${{ github.event.action }}"

  discussion:
    runs-on: ubuntu-latest
    if: github.event.discussion && !github.event.comment
    steps:
    - name: Discussion controling
      run: echo "Triggered on discussion by ${{ github.event.action }}"

  discussion_comment:
    runs-on: ubuntu-latest
    if: github.event.discussion && github.event.comment
    steps:
    - name: Discussion comment controling
      run: echo "Triggered on discussion comment by ${{ github.event.action }}, comment ${{ github.event.comment }}"
