name: Various triggers workflow

on:
  issues:
    types: [opened, edited, deleted, transferred, pinned, unpinned, closed, reopened, assiged, unassigned, labeled, unlabeled, locked, unlocked, milestoned, demilestoned]
  workflow_dispatch:

jobs:
  greet:
    runs-on: ubuntu-latest

    steps:
    - name: Send greeting
      run: echo "Hello triggered ${{ github.event.action }}, labeld ${{ github.event.label.name }}"
