name: Various triggers workflow

on:
  issues:
    types: [opened, edited, deleted, transferred, pinned, unpinned, closed, reopened, assiged, unassigned, labeled, unlabeled, locked, unlocked, milestoned, demilestoned]
  discussion:
    types: [created, edited, deleted, answered, pinned, unpinned, labeled, unlabeled, locked, unlocked]
  workflow_dispatch:

jobs:
  issue:
    runs-on: ubuntu-latest
    if: github.event.issue
    steps:
    - name: Issue controling
      run: echo "Triggered on issue by ${{ github.event.action }}"

  discussion:
    runs-on: ubuntu-latest
    if: github.event.discussion
    steps:
    - name: Discussion controling
      run: echo "Triggered on discussion by ${{ github.event.action }}"
