name: Windows runner

on:
  workflow_dispatch:

jobs:
  windows-runner:
    runs-on: windows-latest
    steps:
      - name: Show OS information
        run: Get-ComputerInfo | Select-Object CsName, WindowsVersion, WindowsBuildLabEx
        shell: pwsh
